server:
  port: 8282

spring:
  application:
    name: chat-service
  ai:
    ollama:
      chat:
        model: llama3
      embedding:
        model: llama3
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
